import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  leetcodeSidebar: [{ type: "autogenerated", dirName: "leetcode" }],
  feSidebar: [{ type: "autogenerated", dirName: "fe" }],
  beSidebar: [{ type: "autogenerated", dirName: "be" }],
  designSystemSidebar: [{ type: "autogenerated", dirName: "designsystem" }],
  languagesSystemSidebar: [{ type: "autogenerated", dirName: "languages" }],
  blockchainSidebar: [{ type: "autogenerated", dirName: "blockchain" }],
  tgSidebar: [{ type: "autogenerated", dirName: "tg_n_ton" }],
};

export default sidebars;
